An Transcript Class Error Fixed
line 74, in showTranscript
    if grade.getLetterGrade() is None:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'getLetterGrade'